[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
